local Constants = require("Sekiro.C0000.Constants")

local M = {}

local STANDARD_QUICK_TURN_DURATION = 20.0 / 60.0

M.SimpleMovementEvents = {
    BaseIdle = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_IDLE,
        state_name = "Idle",
        event = "W_BaseIdle",
        request = "Req_W_Idle",
        duration = 0.0,
    },
    BaseMoveStart = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_START,
        state_name = "MoveStart",
        event = "W_BaseMoveStart",
        request = "Req_W_Event3018",
        duration = 1.6666667,
        -- Regular MoveStart is forced to the forward a000_000400 clip, so all
        -- directions share its end time before entering MoveLoop.
        move_loop_transition_times = {
            [Constants.MOVE_DIRECTION_FORWARD] = 1.6666667,
            [Constants.MOVE_DIRECTION_BACK] = 1.6666667,
            [Constants.MOVE_DIRECTION_LEFT] = 1.6666667,
            [Constants.MOVE_DIRECTION_RIGHT] = 1.6666667,
            [Constants.MOVE_DIRECTION_FORWARD_LEFT] = 1.6666667,
            [Constants.MOVE_DIRECTION_FORWARD_RIGHT] = 1.6666667,
            [Constants.MOVE_DIRECTION_BACK_LEFT] = 1.6666667,
            [Constants.MOVE_DIRECTION_BACK_RIGHT] = 1.6666667,
        },
    },
    BaseMoveLoop = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_LOOP,
        state_name = "MoveLoop",
        event = "W_BaseMoveLoop",
        request = "Req_Event26021_to_EventDummy",
        duration = 0.0,
    },
    BaseMoveStop = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_STOP,
        state_name = "MoveStop",
        event = "W_BaseMoveStop",
        request = "Req_W_Event3026",
        duration = 1.5,
        direction_durations = {
            [Constants.MOVE_DIRECTION_FORWARD] = 1.5,
            [Constants.MOVE_DIRECTION_BACK] = 1.1666667,
            [Constants.MOVE_DIRECTION_LEFT] = 1.0666667,
            [Constants.MOVE_DIRECTION_RIGHT] = 1.0666667,
            [Constants.MOVE_DIRECTION_FORWARD_LEFT] = 1.0666667,
            [Constants.MOVE_DIRECTION_FORWARD_RIGHT] = 1.0666667,
            [Constants.MOVE_DIRECTION_BACK_LEFT] = 1.0666667,
            [Constants.MOVE_DIRECTION_BACK_RIGHT] = 1.0666667,
        },
    },
    BaseQuickTurnLeft45 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_90,
        state_name = "QuickTurn90",
        event = "W_StandQuickTurnLeft45",
        request = "Req_W_Idle",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000010.a000_000010",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_FORWARD_LEFT,
        yaw_delta = -45.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "ground",
        exit_policy = "idle_or_move_start",
    },
    BaseQuickTurnRight45 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_90,
        state_name = "QuickTurn90",
        event = "W_StandQuickTurnRight45",
        request = "Req_W_Idle_Short",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000011.a000_000011",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_FORWARD_RIGHT,
        yaw_delta = 45.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "ground",
        exit_policy = "idle_or_move_start",
    },
    BaseQuickTurnLeft90 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_90,
        state_name = "QuickTurnLeft90",
        event = "W_StandQuickTurnLeft90",
        request = "Req_W_Idle",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000010.a000_000010",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_LEFT,
        yaw_delta = -90.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "ground",
        exit_policy = "idle_or_move_start",
    },
    BaseQuickTurnRight90 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_90,
        state_name = "QuickTurnRight90",
        event = "W_StandQuickTurnRight90",
        request = "Req_W_Idle_Short",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000011.a000_000011",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_RIGHT,
        yaw_delta = 90.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "ground",
        exit_policy = "idle_or_move_start",
    },
    BaseMoveStartQuickTurnLeft90_Bridge = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_START,
        state_name = "MoveStart",
        event = "W_BaseMoveStartQuickTurnLeft90Bridge",
        request = "Req_W_Event3018",
        duration = 1.0 / 60.0,
        exit_time = 1.0 / 60.0,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        use_bridge_source_direction = true,
        exit_policy = "next_event",
        next_event = "BaseMoveStartQuickTurnLeft90",
    },
    BaseMoveStartQuickTurnLeft90 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_90,
        state_name = "QuickTurnLeft90",
        event = "W_StandQuickTurnLeft90",
        request = "Req_W_Idle",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000010.a000_000010",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_LEFT,
        yaw_delta = -90.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_forward_right_to_left_90_chain",
        exit_policy = "idle_or_move_start",
    },
    BaseMoveStartQuickTurnRight90_Bridge = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_START,
        state_name = "MoveStart",
        event = "W_BaseMoveStartQuickTurnRight90Bridge",
        request = "Req_W_Event3018",
        duration = 1.0 / 60.0,
        exit_time = 1.0 / 60.0,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        use_bridge_source_direction = true,
        exit_policy = "next_event",
        next_event = "BaseMoveStartQuickTurnRight90",
    },
    BaseMoveStartQuickTurnRight90 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_90,
        state_name = "QuickTurnRight90",
        event = "W_StandQuickTurnRight90",
        request = "Req_W_Idle_Short",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000011.a000_000011",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_RIGHT,
        yaw_delta = 90.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_forward_left_to_right_90_chain",
        exit_policy = "idle_or_move_start",
    },
    BaseForwardLeftBackRunStop = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_STOP,
        state_name = "MoveStop",
        event = "W_BaseMoveStop",
        request = "Req_W_Event3026",
        duration = 5.0 / 60.0,
        exit_time = 5.0 / 60.0,
        direction = Constants.MOVE_DIRECTION_FORWARD_LEFT,
        exit_policy = "next_event",
        next_event = "BaseForwardLeftBackMoveQuickTurnLeft180Prelude",
    },
    BaseForwardLeftBackMoveQuickTurnLeft180Prelude = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_QUICK_TURN_180,
        state_name = "MoveQuickTurn180",
        event = "W_StandMoveQuickTurnLeft180",
        request = "Req_W_Event3044",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000442.a000_000442",
        duration = 1.0 / 60.0,
        exit_time = 1.0 / 60.0,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        turn_source = "move_forward_left_to_back_stop_turn_left90_chain",
        exit_policy = "next_event",
        next_event = "BaseForwardLeftBackQuickTurnLeft90",
    },
    BaseForwardLeftBackQuickTurnLeft90 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_90,
        state_name = "QuickTurnLeft90",
        event = "W_StandQuickTurnLeft90",
        request = "Req_W_Idle",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000010.a000_000010",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_LEFT,
        yaw_delta = -90.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_forward_left_to_back_stop_turn_left90_chain",
        exit_policy = "idle_or_move_start",
    },
    BaseForwardRightBackRunStop = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_STOP,
        state_name = "MoveStop",
        event = "W_BaseMoveStop",
        request = "Req_W_Event3026",
        duration = 5.0 / 60.0,
        exit_time = 5.0 / 60.0,
        direction = Constants.MOVE_DIRECTION_FORWARD_RIGHT,
        exit_policy = "next_event",
        next_event = "BaseForwardRightBackMoveQuickTurnRight180Prelude",
    },
    BaseForwardRightBackMoveQuickTurnRight180Prelude = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_QUICK_TURN_180,
        state_name = "MoveQuickTurn180",
        event = "W_StandMoveQuickTurnRight180",
        request = "Req_W_Event3045",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000443.a000_000443",
        duration = 1.0 / 60.0,
        exit_time = 1.0 / 60.0,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        turn_source = "move_forward_right_to_back_stop_turn_right90_chain",
        exit_policy = "next_event",
        next_event = "BaseForwardRightBackQuickTurnRight90",
    },
    BaseForwardRightBackQuickTurnRight90 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_90,
        state_name = "QuickTurnRight90",
        event = "W_StandQuickTurnRight90",
        request = "Req_W_Idle_Short",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000011.a000_000011",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_RIGHT,
        yaw_delta = 90.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_forward_right_to_back_stop_turn_right90_chain",
        exit_policy = "idle_or_move_start",
    },
    BaseQuickTurnLeft135 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_180,
        state_name = "QuickTurn180",
        event = "W_StandQuickTurnLeft135",
        request = "Req_W_Event3029",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000012.a000_000012",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_BACK_LEFT,
        yaw_delta = -135.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "ground",
        exit_policy = "idle_or_move_start",
    },
    BaseQuickTurnRight135 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_180,
        state_name = "QuickTurn180",
        event = "W_StandQuickTurnRight135",
        request = "Req_W_Event3028",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000013.a000_000013",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_BACK_RIGHT,
        yaw_delta = 135.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "ground",
        exit_policy = "idle_or_move_start",
    },
    BaseQuickTurnLeft180 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_180,
        state_name = "QuickTurn180",
        event = "W_StandQuickTurnLeft180",
        request = "Req_W_Event3029",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000012.a000_000012",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_LEFT,
        yaw_delta = -180.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "ground",
        exit_policy = "idle_or_move_start",
    },
    BaseQuickTurnRight180 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_180,
        state_name = "QuickTurn180",
        event = "W_StandQuickTurnRight180",
        request = "Req_W_Event3028",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000013.a000_000013",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_RIGHT,
        yaw_delta = 180.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "ground",
        exit_policy = "idle_or_move_start",
    },
    BaseIdleQuickTurnLeft180Prelude = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_MOVE_START_180,
        state_name = "QuickTurnMoveStart180",
        event = "W_StandQuickTurnMoveStartLeft180",
        request = "Req_W_Event3042",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000432.a000_000432",
        duration = 0.0166667,
        exit_time = 0.0166667,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        yaw_delta = 0.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "idle_prelude",
        exit_policy = "quick_turn_180",
        next_event = "BaseQuickTurnLeft180",
    },
    BaseIdleQuickTurnRight180Prelude = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_MOVE_START_180,
        state_name = "QuickTurnMoveStart180",
        event = "W_StandQuickTurnMoveStartRight180",
        request = "Req_W_Event3043",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000433.a000_000433",
        duration = 0.0166667,
        exit_time = 0.0166667,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        yaw_delta = 0.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "idle_prelude",
        exit_policy = "quick_turn_180",
        next_event = "BaseQuickTurnRight180",
    },
    BaseQuickTurnMoveStartLeft135 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_MOVE_START_180,
        state_name = "QuickTurnMoveStart180",
        event = "W_StandQuickTurnMoveStartLeft135",
        request = "Req_W_Event3042",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000132.a000_000132",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_BACK_LEFT,
        yaw_delta = -135.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_start",
        exit_policy = "move_loop",
    },
    BaseQuickTurnMoveStartRight135 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_MOVE_START_180,
        state_name = "QuickTurnMoveStart180",
        event = "W_StandQuickTurnMoveStartRight135",
        request = "Req_W_Event3043",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000133.a000_000133",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_BACK_RIGHT,
        yaw_delta = 135.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_start",
        exit_policy = "move_loop",
    },
    BaseQuickTurnMoveStartLeft180 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_MOVE_START_180,
        state_name = "QuickTurnMoveStart180",
        event = "W_StandQuickTurnMoveStartLeft180",
        request = "Req_W_Event3042",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000432.a000_000432",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        yaw_delta = -180.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_start",
        exit_policy = "move_loop",
    },
    BaseQuickTurnMoveStartRight180 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_QUICK_TURN_MOVE_START_180,
        state_name = "QuickTurnMoveStart180",
        event = "W_StandQuickTurnMoveStartRight180",
        request = "Req_W_Event3043",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000433.a000_000433",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        yaw_delta = 180.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_start",
        exit_policy = "move_loop",
    },
    BaseMoveQuickTurnLeft135 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_QUICK_TURN_180,
        state_name = "MoveQuickTurn180",
        event = "W_StandMoveQuickTurnLeft135",
        request = "Req_W_Event3044",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000442.a000_000442",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_BACK_LEFT,
        yaw_delta = -135.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_loop",
        exit_policy = "move_loop",
    },
    BaseMoveQuickTurnRight135 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_QUICK_TURN_180,
        state_name = "MoveQuickTurn180",
        event = "W_StandMoveQuickTurnRight135",
        request = "Req_W_Event3045",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000443.a000_000443",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_BACK_RIGHT,
        yaw_delta = 135.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_loop",
        exit_policy = "move_loop",
    },
    BaseMoveQuickTurnLeft180 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_QUICK_TURN_180,
        state_name = "MoveQuickTurn180",
        event = "W_StandMoveQuickTurnLeft180",
        request = "Req_W_Event3044",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000442.a000_000442",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        yaw_delta = -180.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_loop",
        exit_policy = "move_loop",
    },
    BaseMoveQuickTurnRight180 = {
        layer = Constants.LAYER_BASE,
        to_state = Constants.BASE_STATE_MOVE_QUICK_TURN_180,
        state_name = "MoveQuickTurn180",
        event = "W_StandMoveQuickTurnRight180",
        request = "Req_W_Event3045",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000443.a000_000443",
        duration = STANDARD_QUICK_TURN_DURATION,
        exit_time = STANDARD_QUICK_TURN_DURATION,
        direction = Constants.MOVE_DIRECTION_FORWARD,
        yaw_delta = 180.0,
        turn_window_start = 0.0,
        turn_window_end = 1.0,
        turn_source = "move_loop",
        exit_policy = "move_loop",
    },
}

M.SimpleActionEvents = {
    ActionItemGourdDrinkIdle = {
        input_event = "ActionItemGourdDrink",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_ITEM_GOURD_DRINK,
        state_name = "ActionItemGourdDrinkIdle",
        event = "W_ItemGourdDrink",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_250000.a000_250000",
        duration = 2.0,
    },
    ActionItemGourdDrinkMove = {
        input_event = "ActionItemGourdDrink",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_ITEM_GOURD_DRINK_MOVE,
        state_name = "ActionItemGourdDrinkMove",
        event = "W_ItemGourdDrinkMove",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_250000.a000_250000",
        duration = 2.0,
    },
    ActionSubWeaponExpandIdle = {
        input_event = "ActionSubWeaponExpand",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_SUB_WEAPON_EXPAND,
        state_name = "ActionSubWeaponExpandIdle",
        event = "W_SubWeaponExpand",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a070_412000.a070_412000",
        duration = 1.34,
    },
    ActionSubWeaponExpandMove = {
        input_event = "ActionSubWeaponExpand",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_SUB_WEAPON_EXPAND_MOVE,
        state_name = "ActionSubWeaponExpandMove",
        event = "W_SubWeaponExpandMove",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a070_412001.a070_412001",
        duration = 1.34,
    },
    ActionLeftWaistDrawIdle = {
        input_event = "ActionLeftWaistDraw",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_LEFT_WAIST_DRAW,
        state_name = "ActionLeftWaistDrawIdle",
        event = "W_GroundNonCombatAreaLeave",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_700510.a000_700510",
        duration = 1.4333333,
        weapon_event = "left_waist_draw",
        weapon_right_hand_time = 0.16666667,
        weapon_right_hand_align_until = 0.5,
        weapon_switch_time = 0.5,
    },
    ActionLeftWaistDrawMove = {
        input_event = "ActionLeftWaistDraw",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_LEFT_WAIST_DRAW_MOVE,
        state_name = "ActionLeftWaistDrawMove",
        event = "W_GroundNonCombatAreaMoveLeave",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_700511.a000_700511",
        duration = 1.4333333,
        weapon_event = "left_waist_draw",
        weapon_right_hand_time = 0.16666667,
        weapon_right_hand_align_until = 0.5,
        weapon_switch_time = 0.5,
    },
    ActionLeftWaistSheatheIdle = {
        input_event = "ActionLeftWaistSheathe",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_LEFT_WAIST_SHEATHE,
        state_name = "ActionLeftWaistSheatheIdle",
        event = "W_GroundNonCombatAreaEnter",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_700500.a000_700500",
        duration = 2.1,
        weapon_event = "left_waist_sheathe",
        weapon_switch_time = 0.46666667,
    },
    ActionLeftWaistSheatheMove = {
        input_event = "ActionLeftWaistSheathe",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_LEFT_WAIST_SHEATHE_MOVE,
        state_name = "ActionLeftWaistSheatheMove",
        event = "W_GroundNonCombatAreaMoveEnter",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_700501.a000_700501",
        duration = 2.1,
        weapon_event = "left_waist_sheathe",
        weapon_switch_time = 0.46666667,
    },
    DeflectGuardIdle = {
        input_event = "DeflectGuard",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_DEFLECT_GUARD_IDLE,
        state_name = "DeflectGuardIdle",
        event = "W_DeflectGuardIdle",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_002000.a050_002000",
        duration = 3.0,
        hold_until_release = true,
    },
    DeflectGuardMoveForward = {
        input_event = "DeflectGuard",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_DEFLECT_GUARD_MOVE_FORWARD,
        state_name = "DeflectGuardMoveForward",
        event = "W_DeflectGuardMove",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_002200.a050_002200",
        duration = 1.3333334,
        hold_until_release = true,
        direction = Constants.MOVE_DIRECTION_FORWARD,
    },
    DeflectGuardMoveBack = {
        input_event = "DeflectGuard",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_DEFLECT_GUARD_MOVE_BACK,
        state_name = "DeflectGuardMoveBack",
        event = "W_DeflectGuardMove",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_002201.a050_002201",
        duration = 1.3333334,
        hold_until_release = true,
        direction = Constants.MOVE_DIRECTION_BACK,
    },
    DeflectGuardMoveLeft = {
        input_event = "DeflectGuard",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_DEFLECT_GUARD_MOVE_LEFT,
        state_name = "DeflectGuardMoveLeft",
        event = "W_DeflectGuardMove",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_002202.a050_002202",
        duration = 1.3333334,
        hold_until_release = true,
        direction = Constants.MOVE_DIRECTION_LEFT,
    },
    DeflectGuardMoveRight = {
        input_event = "DeflectGuard",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_DEFLECT_GUARD_MOVE_RIGHT,
        state_name = "DeflectGuardMoveRight",
        event = "W_DeflectGuardMove",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_002203.a050_002203",
        duration = 1.3333334,
        hold_until_release = true,
        direction = Constants.MOVE_DIRECTION_RIGHT,
    },
    DeflectGuardToStand = {
        input_event = "DeflectGuardRelease",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_DEFLECT_GUARD_TO_STAND,
        state_name = "DeflectGuardToStand",
        event = "W_DeflectGuardToStand",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_203010.a050_203010",
        duration = 0.67,
    },
    GroundAttackCombo1 = {
        input_event = "GroundAttack",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_1,
        state_name = "GroundAttackCombo1",
        event = "W_GroundAttackCombo1",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300000.a050_300000",
        duration = 2.267,
    },
    GroundAttackCombo1Release = {
        input_event = "GroundAttackRelease",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_1_RELEASE,
        state_name = "GroundAttackCombo1Release",
        event = "W_GroundAttackCombo1Release",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300100.a050_300100",
        duration = 1.733,
    },
    GroundAttackCombo1Reverse = {
        input_event = "GroundAttack",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_1_REVERSE,
        state_name = "GroundAttackCombo1Reverse",
        event = "W_GroundAttackCombo1Reverse",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300001.a050_300001",
        duration = 2.267,
    },
    GroundAttackCombo1ReverseRelease = {
        input_event = "GroundAttackRelease",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_1_REVERSE_RELEASE,
        state_name = "GroundAttackCombo1ReverseRelease",
        event = "W_GroundAttackCombo1ReverseRelease",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300101.a050_300101",
        duration = 1.733,
    },
    GroundAttackCombo2 = {
        input_event = "GroundAttack",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_2,
        state_name = "GroundAttackCombo2",
        event = "W_GroundAttackCombo2",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300010.a050_300010",
        duration = 2.267,
    },
    GroundAttackCombo2Release = {
        input_event = "GroundAttackRelease",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_2_RELEASE,
        state_name = "GroundAttackCombo2Release",
        event = "W_GroundAttackCombo2Release",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300110.a050_300110",
        duration = 1.633,
    },
    GroundAttackCombo2Reverse = {
        input_event = "GroundAttack",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_2_REVERSE,
        state_name = "GroundAttackCombo2Reverse",
        event = "W_GroundAttackCombo2Reverse",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300011.a050_300011",
        duration = 2.267,
    },
    GroundAttackCombo2ReverseRelease = {
        input_event = "GroundAttackRelease",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_2_REVERSE_RELEASE,
        state_name = "GroundAttackCombo2ReverseRelease",
        event = "W_GroundAttackCombo2ReverseRelease",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300111.a050_300111",
        duration = 1.733,
    },
    GroundAttackCombo3 = {
        input_event = "GroundAttack",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_3,
        state_name = "GroundAttackCombo3",
        event = "W_GroundAttackCombo3",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300020.a050_300020",
        duration = 2.033,
    },
    GroundAttackCombo4 = {
        input_event = "GroundAttack",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_4,
        state_name = "GroundAttackCombo4",
        event = "W_GroundAttackCombo4",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300030.a050_300030",
        duration = 2.033,
    },
    GroundAttackCombo5 = {
        input_event = "GroundAttack",
        layer = Constants.LAYER_ACTION,
        to_state = Constants.ACTION_STATE_GROUND_ATTACK_COMBO_5,
        state_name = "GroundAttackCombo5",
        event = "W_GroundAttackCombo5",
        anim_asset = "/Game/Animation/Sekiro/C0000/GroundAttack_SM/a050_300040.a050_300040",
        duration = 2.033,
    },
}

M.SimpleReactionEvents = {
    ReactionDeflectGuardIdle = {
        input_event = "ReactionDeflectGuard",
        layer = Constants.LAYER_REACTION,
        to_state = Constants.REACTION_STATE_DEFLECT_GUARD,
        state_name = "ReactionDeflectGuardIdle",
        event = "W_DeflectGuardToStand",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_203010.a050_203010",
        duration = 0.67,
    },
    ReactionDeflectGuardMove = {
        input_event = "ReactionDeflectGuard",
        layer = Constants.LAYER_REACTION,
        to_state = Constants.REACTION_STATE_DEFLECT_GUARD_MOVE,
        state_name = "ReactionDeflectGuardMove",
        event = "W_DeflectGuardToStandMove",
        anim_asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a050_203011.a050_203011",
        duration = 0.67,
    },
}

M.StandMovePulseEvents = {
    W_StandMoveStart = {
        request = "Req_W_Event3018",
        followup = "Req_W_Event3019",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000100.a000_000100",
    },
    W_StandMoveStartFromFreeFall = {
        request = "Req_Event26031_to_EventDummy",
        followup = "Req_Event26011_to_EventDummy",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000110.a000_000110",
    },
    W_StandMoveStartFromFreeFallShortStiff = {
        request = "Req_W_CoverEnd",
        followup = "Req_W_CoverActionStart",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000120.a000_000120",
    },
    W_StandMoveStartFromLandGroundPositioningJump = {
        request = "Req_W_CoverIdle",
        followup = "Req_W_CoverLookThrowGrab",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000110.a000_000110",
    },
    W_StandWalkStop = {
        request = "Req_W_Event3026",
        followup = "Return_To_StandMove",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000300.a000_000300",
    },
    W_StandRunStop = {
        request = "Req_W_Event3027",
        followup = "Return_To_StandMove",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000600.a000_000600",
    },
    W_StandQuickTurnRight180 = {
        request = "Req_W_Event3028",
        followup = "Return_To_StandMove",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000013.a000_000013",
    },
    W_StandQuickTurnLeft180 = {
        request = "Req_W_Event3029",
        followup = "Return_To_StandMove",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000012.a000_000012",
    },
    W_StandQuickTurnMoveStartLeft180 = {
        request = "Req_W_Event3042",
        followup = "Req_W_Event3038",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000132.a000_000132",
    },
    W_StandQuickTurnMoveStartRight180 = {
        request = "Req_W_Event3043",
        followup = "Req_W_Event3039",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000133.a000_000133",
    },
    W_StandMoveQuickTurnLeft180 = {
        request = "Req_W_Event3044",
        followup = "Req_W_Event3040",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000442.a000_000442",
    },
    W_StandMoveQuickTurnRight180 = {
        request = "Req_W_Event3045",
        followup = "Req_W_Event3041",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000443.a000_000443",
    },
    W_StandQuickTurnLeft90 = {
        request = "Req_W_Idle",
        followup = "Return_To_StandMove",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000010.a000_000010",
    },
    W_StandQuickTurnRight90 = {
        request = "Req_W_Idle_Short",
        followup = "Return_To_StandMove",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000011.a000_000011",
    },
    W_StandMoveStartFromSprint = {
        request = "Req_W_WideshotRightStart_mirror",
        followup = "Req_a000_00000000_End",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000450.a000_000450",
    },
}

M.PulseOnlyEvents = {
    W_StandMoveLoop = {
        request = "Req_Event26021_to_EventDummy",
    },
    W_StandMoveLoopSync = {
        request = "Req_Event26021_to_EventDummy",
    },
    W_StandMoveLoopFromSprint = {
        request = "Req_a000_00000000_End",
        followup = "Req_a000_00000001_End",
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_000160.a000_000160",
    },
}

M.OverwriteLowerEvents = {
    W_StandMoveLowerStart = {
        top_level_request = "Req_W_ChargeShotRightEnd",
        request = "Req_W_AttackBoundParry_Add01",
        followup = "Req_W_AttackBoundGuard_Add04",
        asset = "/Game/Animation/Sekiro/C0000/StandMoveLower_SM/a000_000100.a000_000100",
    },
}

M.ActionIdleEvents = {
    W_ItemPillTonic = {
        state_id = 0,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_250300.a000_250300",
    },
    W_DeflectGuardIdle = {
        state_id = 409,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_002000.a050_002000",
    },
    W_DeflectGuardMove = {
        state_id = 410,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_002200.a050_002200",
    },
    W_DeflectGuardToStand = {
        state_id = 120,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_203010.a050_203010",
    },
    W_DeflectGuardToStandVariation = {
        state_id = 121,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a050_203015.a050_203015",
    },
    W_SubWeaponExpand = {
        state_id = 133,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a070_412000.a070_412000",
    },
    W_GroundNonCombatAreaEnter = {
        state_id = 19260,
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_700500.a000_700500",
    },
    W_GroundNonCombatAreaLeave = {
        state_id = 19261,
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_700510.a000_700510",
    },
    W_GroundSubAttackCombo1Moveable = {
        state_id = 134,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a079_400000.a079_400000",
    },
    W_GroundSubAttackCombo1ReleaseMoveable = {
        state_id = 135,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a079_400100.a079_400100",
    },
    W_GroundSubAttackLockOnMoveable = {
        state_id = 136,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a079_400600.a079_400600",
    },
    W_GroundSubAttackLockOnReleaseMoveable = {
        state_id = 137,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a079_400650.a079_400650",
    },
    W_ItemFailed = {
        state_id = 138,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_259000.a000_259000",
    },
    W_ItemGourdDrink = {
        state_id = 200,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_250000.a000_250000",
    },
    W_ItemGourdDrinkFailed = {
        state_id = 201,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_250005.a000_250005",
    },
    W_ItemGourdDrinkRepeat = {
        state_id = 210,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_250001.a000_250001",
    },
    W_ItemGourdDrinkRepeatFailed = {
        state_id = 211,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_250006.a000_250006",
    },
    W_ItemAntiHallucinogen = {
        state_id = 220,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_251800.a000_251800",
    },
    W_ItemPowderMedicineRecoverPoison = {
        state_id = 221,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_251600.a000_251600",
    },
    W_ItemStone = {
        state_id = 230,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_251400.a000_251400",
    },
    W_ItemPaperDollExchangeWhite = {
        state_id = 240,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_250600.a000_250600",
    },
    W_SubWeaponExpand2 = {
        state_id = 241,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a070_412003.a070_412003",
    },
    W_SubWeaponExpand3 = {
        state_id = 242,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a070_412006.a070_412006",
    },
    W_GroundSubAttackHoldLoop = {
        state_id = 250,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a072_400300.a072_400300",
    },
    W_ItemOhagi = {
        state_id = 260,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_252000.a000_252000",
    },
    W_ItemKaki = {
        state_id = 261,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_252100.a000_252100",
    },
    W_ItemAntiGhostBuff = {
        state_id = 262,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_251300.a000_251300",
    },
    W_ItemPottery = {
        state_id = 263,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveableAction_SM/a000_252200.a000_252200",
    },
}

M.ActionMoveEvents = {
    W_ItemPillTonicMove = {
        state_id = 0,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_250300.a000_250300",
    },
    W_DeflectGuardToStandMove = {
        state_id = 120,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a050_203011.a050_203011",
    },
    W_DeflectGuardToStandMoveVariation = {
        state_id = 121,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a050_203016.a050_203016",
    },
    W_SubWeaponExpandMove = {
        state_id = 133,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a070_412001.a070_412001",
    },
    W_GroundNonCombatAreaMoveEnter = {
        state_id = 19262,
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_700501.a000_700501",
    },
    W_GroundNonCombatAreaMoveLeave = {
        state_id = 19263,
        asset = "/Game/Animation/Sekiro/C0000/StandMove_SM/a000_700511.a000_700511",
    },
    W_GroundSubAttackCombo1Move = {
        state_id = 134,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a079_400000.a079_400000",
    },
    W_GroundSubAttackCombo1ReleaseMove = {
        state_id = 135,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a079_400100.a079_400100",
    },
    W_GroundSubAttackLockOnMove = {
        state_id = 136,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a079_400600.a079_400600",
    },
    W_GroundSubAttackLockOnReleaseMove = {
        state_id = 137,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a079_400650.a079_400650",
    },
    W_ItemFailedMove = {
        state_id = 138,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_259000.a000_259000",
    },
    W_ItemGourdDrinkMove = {
        state_id = 200,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_250000.a000_250000",
    },
    W_ItemGourdDrinkFailedMove = {
        state_id = 201,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_250005.a000_250005",
    },
    W_ItemGourdDrinkRepeatMove = {
        state_id = 210,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_250001.a000_250001",
    },
    W_ItemGourdDrinkRepeatFailedMove = {
        state_id = 211,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_250006.a000_250006",
    },
    W_ItemAntiHallucinogenMove = {
        state_id = 220,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_251800.a000_251800",
    },
    W_ItemPowderMedicineRecoverPoisonMove = {
        state_id = 221,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_251600.a000_251600",
    },
    W_ItemStoneMove = {
        state_id = 230,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_251400.a000_251400",
    },
    W_ItemPaperDollExchangeWhiteMove = {
        state_id = 240,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_250600.a000_250600",
    },
    W_SubWeaponExpand2Move = {
        state_id = 241,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a070_412004.a070_412004",
    },
    W_SubWeaponExpand3Move = {
        state_id = 242,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a070_412007.a070_412007",
    },
    W_GroundSubAttackHoldMove = {
        state_id = 250,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a072_400300.a072_400300",
    },
    W_ItemOhagiMove = {
        state_id = 260,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_252000.a000_252000",
    },
    W_ItemKakiMove = {
        state_id = 261,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_252100.a000_252100",
    },
    W_ItemAntiGhostBuffMove = {
        state_id = 262,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_251300.a000_251300",
    },
    W_ItemPotteryMove = {
        state_id = 263,
        asset = "/Game/Animation/Sekiro/C0000/StandMoveUpper_SM/a000_252200.a000_252200",
    },
}

return M
