import json
import os
import traceback

import unreal


PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
EXPORT_ROOT = os.path.join(PROJECT_ROOT, "Intermediate", "SekiroExports", "wp_a_0310")
FBX_SOURCE = os.path.join(EXPORT_ROOT, "c0000_bindpose.fbx")
OBJ_SOURCE_DIR = os.path.join(PROJECT_ROOT, "ImportSource", "Sekiro", "Weapons", "WP_A_0310", "Obj")
TEXTURE_SOURCE_DIR = os.path.join(PROJECT_ROOT, "ImportSource", "Sekiro", "Weapons", "WP_A_0310", "TexturesTga")
DESTINATION = "/Game/Animation/Sekiro/C0000/Weapons"
STATIC_MESH_NAME = "SM_WP_A_0310_MortalBlade"
SPLIT_STATIC_MESHES = [
    {
        "source": os.path.join(OBJ_SOURCE_DIR, "WP_A_0310.obj"),
        "asset_name": "SM_WP_A_0310_MortalBlade_Sheathed",
        "description": "WP_A_0310.flver, assembled/sheath-side source mesh",
    },
    {
        "source": os.path.join(OBJ_SOURCE_DIR, "WP_A_0310_1.obj"),
        "asset_name": "SM_WP_A_0310_MortalBlade_DrawBlade",
        "description": "WP_A_0310_1.flver, drawn blade source mesh",
    },
]
REPORT_PATH = os.path.join(PROJECT_ROOT, "Saved", "SekiroImportReports", "wp_a_0310_import_summary.json")


TEXTURE_USAGE = {
    "wp_a_0310_weapon01_a": "color",
    "wp_a_0310_weapon01_m": "mask",
    "wp_a_0310_weapon01_n": "normal",
    "wp_a_0310_weapon02_a": "color",
    "wp_a_0310_weapon02_m": "mask",
    "wp_a_0310_weapon02_n": "normal",
}

MATERIAL_DEFS = {
    "M_WP_A_0310_Weapon01": {
        "color": "wp_a_0310_weapon01_a",
        "normal": "wp_a_0310_weapon01_n",
    },
    "M_WP_A_0310_Weapon02": {
        "color": "wp_a_0310_weapon02_a",
        "normal": "wp_a_0310_weapon02_n",
    },
}

FBX_AUTOGENERATED_MATERIALS_TO_REMOVE = [
    "f0_M_WP_A_0310_wepon01",
    "f1_M_WP_A_0310_wepon01",
    "M_WP_A_0310_wepon01",
    "M_WP_A_0310_wepon02",
    "Material__142",
    "wp_a_0310_weapon01",
]


def log(message: str) -> None:
    unreal.log(message)
    print(message)


def ensure_directory(asset_path: str) -> None:
    if unreal.EditorAssetLibrary.does_directory_exist(asset_path):
        return
    if not unreal.EditorAssetLibrary.make_directory(asset_path):
        raise RuntimeError(f"Failed to create directory: {asset_path}")


def try_set(obj, property_name: str, value) -> bool:
    try:
        obj.set_editor_property(property_name, value)
        return True
    except Exception as exc:
        log(f"[WP_A_0310] Skip property {property_name}: {exc}")
        return False


def create_import_task(filename: str, destination_path: str, destination_name: str | None = None, options=None):
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", filename)
    task.set_editor_property("destination_path", destination_path)
    if destination_name:
        task.set_editor_property("destination_name", destination_name)
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("replace_existing_settings", True)
    task.set_editor_property("save", True)
    if options:
        task.set_editor_property("options", options)
    return task


def create_static_mesh_import_options():
    options = unreal.FbxImportUI()
    try_set(options, "automated_import_should_detect_type", False)
    try_set(options, "original_import_type", unreal.FBXImportType.FBXIT_STATIC_MESH)
    try_set(options, "mesh_type_to_import", unreal.FBXImportType.FBXIT_STATIC_MESH)
    try_set(options, "import_as_skeletal", False)
    try_set(options, "import_mesh", True)
    try_set(options, "import_animations", False)
    # UE 5.7 Interchange cannot import the embedded Sekiro BC DDS payloads in commandlet.
    # Textures are converted to TGA and imported separately below.
    try_set(options, "import_materials", False)
    try_set(options, "import_textures", False)

    static_mesh_data = options.get_editor_property("static_mesh_import_data")
    try_set(static_mesh_data, "combine_meshes", True)
    try_set(static_mesh_data, "convert_scene", True)
    try_set(static_mesh_data, "convert_scene_unit", True)
    try_set(static_mesh_data, "generate_lightmap_u_vs", True)
    try_set(static_mesh_data, "auto_generate_collision", False)
    try_set(
        static_mesh_data,
        "normal_import_method",
        unreal.FBXNormalImportMethod.FBXNIM_IMPORT_NORMALS_AND_TANGENTS,
    )
    return options


def import_asset_tasks(tasks):
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks(tasks)
    results = []
    for task in tasks:
        results.append([str(path) for path in task.get_editor_property("imported_object_paths")])
    return results


def import_static_mesh() -> dict:
    if not os.path.isfile(FBX_SOURCE):
        raise RuntimeError(f"FBX source not found: {FBX_SOURCE}")

    mesh_asset_path = f"{DESTINATION}/{STATIC_MESH_NAME}.{STATIC_MESH_NAME}"
    existing_mesh_asset = unreal.load_asset(mesh_asset_path)
    if existing_mesh_asset:
        return {
            "source": FBX_SOURCE,
            "asset_path": mesh_asset_path,
            "imported_object_paths": [],
            "skipped_existing": True,
            "material_slot_count": len(existing_mesh_asset.get_editor_property("static_materials")),
        }

    task = create_import_task(FBX_SOURCE, DESTINATION, STATIC_MESH_NAME, create_static_mesh_import_options())
    [imported_paths] = import_asset_tasks([task])
    mesh_asset = unreal.load_asset(mesh_asset_path)
    if not mesh_asset:
        raise RuntimeError(f"Static mesh import did not create {mesh_asset_path}")

    unreal.EditorAssetLibrary.save_loaded_asset(mesh_asset)
    return {
        "source": FBX_SOURCE,
        "asset_path": mesh_asset_path,
        "imported_object_paths": imported_paths,
        "material_slot_count": len(mesh_asset.get_editor_property("static_materials")),
    }


def import_split_static_meshes() -> list[dict]:
    reports = []
    for mesh_info in SPLIT_STATIC_MESHES:
        source = mesh_info["source"]
        asset_name = mesh_info["asset_name"]
        asset_path = f"{DESTINATION}/{asset_name}.{asset_name}"
        existing_mesh = unreal.load_asset(asset_path)
        if existing_mesh:
            reports.append(
                {
                    "source": source,
                    "asset_path": asset_path,
                    "description": mesh_info["description"],
                    "skipped_existing": True,
                    "material_slot_count": len(existing_mesh.get_editor_property("static_materials")),
                }
            )
            continue

        if not os.path.isfile(source):
            raise RuntimeError(f"Split static mesh source not found: {source}")

        task = create_import_task(source, DESTINATION, asset_name)
        [imported_paths] = import_asset_tasks([task])
        mesh_asset = unreal.load_asset(asset_path)
        if not mesh_asset:
            raise RuntimeError(f"Split static mesh import did not create {asset_path}")
        unreal.EditorAssetLibrary.save_loaded_asset(mesh_asset)
        reports.append(
            {
                "source": source,
                "asset_path": asset_path,
                "description": mesh_info["description"],
                "imported_object_paths": imported_paths,
                "material_slot_count": len(mesh_asset.get_editor_property("static_materials")),
            }
        )

    return reports


def import_textures() -> dict:
    if not os.path.isdir(TEXTURE_SOURCE_DIR):
        raise RuntimeError(f"Texture source directory not found: {TEXTURE_SOURCE_DIR}")

    tasks = []
    skipped_existing = []
    for filename in sorted(os.listdir(TEXTURE_SOURCE_DIR)):
        if not filename.lower().endswith(".tga"):
            continue
        texture_name = os.path.splitext(filename)[0]
        texture_asset_path = f"{DESTINATION}/{texture_name}.{texture_name}"
        if unreal.EditorAssetLibrary.does_asset_exist(texture_asset_path):
            skipped_existing.append(texture_asset_path)
            continue
        tasks.append(create_import_task(os.path.join(TEXTURE_SOURCE_DIR, filename), DESTINATION, texture_name))

    imported_paths = import_asset_tasks(tasks) if tasks else []
    configured = []
    for texture_name, usage in TEXTURE_USAGE.items():
        asset_path = f"{DESTINATION}/{texture_name}.{texture_name}"
        texture_asset = unreal.load_asset(asset_path)
        if not texture_asset:
            continue

        try_set(texture_asset, "srgb", usage == "color")
        if usage == "normal":
            try_set(texture_asset, "compression_settings", unreal.TextureCompressionSettings.TC_NORMALMAP)
        elif usage == "mask":
            try_set(texture_asset, "compression_settings", unreal.TextureCompressionSettings.TC_MASKS)
        else:
            try_set(texture_asset, "compression_settings", unreal.TextureCompressionSettings.TC_DEFAULT)
        unreal.EditorAssetLibrary.save_loaded_asset(texture_asset)
        configured.append({"asset_path": asset_path, "usage": usage})

    return {
        "source_directory": TEXTURE_SOURCE_DIR,
        "task_count": len(tasks),
        "skipped_existing": skipped_existing,
        "imported_object_paths": imported_paths,
        "configured_textures": configured,
    }


def get_or_create_material(material_name: str, color_texture_name: str, normal_texture_name: str):
    material_path = f"{DESTINATION}/{material_name}.{material_name}"
    material = unreal.load_asset(material_path)
    created = False
    if not material:
        material = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            material_name,
            DESTINATION,
            unreal.Material,
            unreal.MaterialFactoryNew(),
        )
        if not material:
            raise RuntimeError(f"Failed to create material: {material_name}")
        created = True

    color_texture = unreal.load_asset(f"{DESTINATION}/{color_texture_name}.{color_texture_name}")
    normal_texture = unreal.load_asset(f"{DESTINATION}/{normal_texture_name}.{normal_texture_name}")
    if not color_texture or not normal_texture:
        raise RuntimeError(f"Missing textures for {material_name}: {color_texture_name}, {normal_texture_name}")

    if created:
        color_sample = unreal.MaterialEditingLibrary.create_material_expression(
            material,
            unreal.MaterialExpressionTextureSample,
            -400,
            -80,
        )
        color_sample.set_editor_property("texture", color_texture)
        unreal.MaterialEditingLibrary.connect_material_property(
            color_sample,
            "RGB",
            unreal.MaterialProperty.MP_BASE_COLOR,
        )

        normal_sample = unreal.MaterialEditingLibrary.create_material_expression(
            material,
            unreal.MaterialExpressionTextureSample,
            -400,
            160,
        )
        normal_sample.set_editor_property("texture", normal_texture)
        try_set(normal_sample, "sampler_type", unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL)
        unreal.MaterialEditingLibrary.connect_material_property(
            normal_sample,
            "RGB",
            unreal.MaterialProperty.MP_NORMAL,
        )

    try_set(material, "two_sided", True)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    return material, created


def assign_materials_to_mesh(mesh_asset_name: str) -> dict:
    mesh_path = f"{DESTINATION}/{mesh_asset_name}.{mesh_asset_name}"
    mesh = unreal.load_asset(mesh_path)
    if not mesh:
        raise RuntimeError(f"Static mesh not found for material assignment: {mesh_path}")

    materials = {}
    created_materials = []
    for material_name, definition in MATERIAL_DEFS.items():
        material, created = get_or_create_material(material_name, definition["color"], definition["normal"])
        materials[material_name] = material
        if created:
            created_materials.append(material.get_path_name())

    assignments = []
    static_materials = mesh.get_editor_property("static_materials")
    for slot_index, static_material in enumerate(static_materials):
        slot_name = str(static_material.get_editor_property("material_slot_name")).lower()
        target_material = None
        if "weapon02" in slot_name or "wepon02" in slot_name:
            target_material = materials["M_WP_A_0310_Weapon02"]
        elif "weapon01" in slot_name or "wepon01" in slot_name or "material__142" in slot_name:
            target_material = materials["M_WP_A_0310_Weapon01"]

        if target_material:
            mesh.set_material(slot_index, target_material)
            assignments.append(
                {
                    "slot_index": slot_index,
                    "slot_name": slot_name,
                    "material": target_material.get_path_name(),
                }
            )

    unreal.EditorAssetLibrary.save_loaded_asset(mesh)
    return {
        "mesh": mesh_path,
        "created_materials": created_materials,
        "assignments": assignments,
    }


def create_and_assign_materials() -> dict:
    mesh_names = [STATIC_MESH_NAME] + [item["asset_name"] for item in SPLIT_STATIC_MESHES]
    return {
        "mesh_reports": [assign_materials_to_mesh(mesh_name) for mesh_name in mesh_names],
    }


def cleanup_autogenerated_materials() -> list[str]:
    removed = []
    for asset_name in FBX_AUTOGENERATED_MATERIALS_TO_REMOVE:
        asset_path = f"{DESTINATION}/{asset_name}.{asset_name}"
        if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
            if unreal.EditorAssetLibrary.delete_asset(asset_path):
                removed.append(asset_path)
    return removed


def list_destination_assets() -> list[dict]:
    assets = unreal.EditorAssetLibrary.list_assets(DESTINATION, recursive=False, include_folder=False)
    result = []
    for asset_path in sorted(assets):
        if "0310" not in asset_path:
            continue
        asset = unreal.load_asset(asset_path)
        result.append(
            {
                "path": asset_path,
                "class": asset.get_class().get_name() if asset else None,
            }
        )
    return result


def write_report(report: dict) -> None:
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as handle:
        json.dump(report, handle, ensure_ascii=False, indent=2)


def main() -> None:
    ensure_directory(DESTINATION)
    report = {
        "destination": DESTINATION,
        "static_mesh": import_static_mesh(),
        "split_static_meshes": import_split_static_meshes(),
        "textures": import_textures(),
    }
    report["materials"] = create_and_assign_materials()
    report["removed_autogenerated_materials"] = cleanup_autogenerated_materials()
    report["destination_assets"] = list_destination_assets()
    write_report(report)
    log(f"[WP_A_0310] Import complete. Report: {REPORT_PATH}")


try:
    main()
except Exception as exc:
    error_report = {
        "error": str(exc),
        "traceback": traceback.format_exc(),
    }
    write_report(error_report)
    log(f"[WP_A_0310] Import failed: {exc}")
    raise
